name: Merge Into Master
on:
  pull_request:
    branches:
      - master
    types: [closed]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Tag Master
        uses: rennemannd/auto/tag
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"